name: C/C++ Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: install-depends
      run: sudo apt install -y libboost-all-dev libsqlite3-dev libasio-dev nasm
    - name: build-x264
      run: cd x264; make -j 5; cd ..
    - name: build-zstd
      run: cd zstd; make -j 5; cd ..
    - name: make
      run: make