name: C/C++ Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: install-depends
      run: sudo apt install -y build-essential libboost-all-dev libsqlite3-dev libasio-dev nasm cmake
    - name: install-ffmpeg
      run: sudo apt install -y ffmpeg libswscale-dev libavutil-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libpostproc-dev libswresample-dev
    - name: build-x264
      run: cd x264; make -j 5; cd ..
    - name: build-zstd
      run: cd zstd; make -j 5; cd ..
    - name: cmake
      run: cmake .; exit 0
    - name: make
      run: make -j 5